#!/bin/bash

OS=""

case "$OSTYPE" in
    linux-gnu*) OS="Linux" ;;
    darwin*)    OS="Mac"   ;;
    *)          echo "OS not supported: $OSTYPE"
                exit 1     ;;
esac 

# flag for deleting original file upon encryption/decryption.
delete_original_file=false

if [[ "$2" == "--rm-orig" || "$3" == "--rm-orig" || "$4" == "--rm-orig" ]]; then
    delete_original_file=true
fi

sign_data=true

if [[ "$2" == "--no-sign" || "$3" = "--no-sign" || "$4" == "--no-sign" ]]; then
    sign_data=false
fi 

key_lookup() {
    if ! gpg --list-keys "$1" > /dev/null 2>&1; then
        echo "Recipient key not found! Remember to import first."
    fi
}

show_help() {
    echo "It is recommended to make the script an alias!"
    echo "Usage: $0 {encrypt|decrypt} <arguments>"
    echo "Options:"
    echo "   encrypt <RECIPIENT_EMAIL> <FILE_TO_ENCRYPT>    Encrypt + sign to a recipient"
    echo "   decrypt <FILE_TO_DECRYPT>                      Decrypt a given file"
    echo "   pb_encrypt <RECIPIENT_EMAIL>                   Encrypt clipboard contents"
    echo "   pb_decrypt                                     Decrypt clipboard contents"
    echo "   --rm-orig                                      Remove original file upon encrypt/decrypt"
    echo "   --no-sign                                      Omits signature upon encryption"
    echo "   -h, --help                                     Display this help message"
}

file_encrypt() {
    local recipient="$1"
    local file_input="$2"
    local file_output="${file_input}.asc"

    key_lookup "$recipient"

    if $sign_data; then
        gpg --output "$file_output" \
            --encrypt --sign --armor \
            --recipient "$recipient" "$file_input"
    else
        gpg --output "$file_output" \
            --encrypt --armor \
            --recipient "$recipient" "$file_input"
    fi

    if $delete_original_file; then
        rm "$file_input"
    fi
}

file_decrypt() {
    local file_encrypted="$1"
    local file_output="${file_encrypted}.decrypted"

    gpg --output "$file_output" \
        --decrypt "$file_encrypted"

    echo "'$file_encrypted' decrypted as '$file_output.'"

    if $delete_original_file; then
        rm "$file_encrypted"
        echo "Original encrypted file '$file_encrypted' deleted."
    fi
}


clipboard_encrypt() {
    local recipient="$1"

    if [[ "$OS" == "Mac" ]]; then
        if $sign_data; then 
            pbpaste | gpg --armor --encrypt --sign --recipient "$recipient" | pbcopy
        else
            pbpaste | gpg --armor --encrypt --recipient "$recipient" | pbcopy
    fi
            

    elif [[ "$OS" == "Linux" ]] then 
        if $sign_data; then
            xclip -o | gpg --armor --encrypt --sign --recipient "$recipient" | xclip -selection clipboard
        else 
            xclip -o | gpg --armor --encrypt --recipient "$recipient" | xclip -selection clipboard
        fi
    fi
}

clipboard_decrypt() {

    if [[ "$OS" == "Mac" ]]; then
        pbpaste | gpg --decrypt | pbcopy
    elif [[ "$OS" == "Linux" ]] then
        xclip -o | gpg --decrypt | xclip -selection clipboard
    fi 
    
    echo "successfully decrypted text copied from clipboard!"
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    show_help
    exit 0
fi

case "$1" in
    encrypt)
        if [[ -n "$2" && -n "$3" ]]; then
            file_encrypt "$2" "$3" "$delete_original_file"
        else
            echo "Usage: $0 encrypt <RECIPIENT_EMAIL> <FILE_TO_ENCRYPT> [--rm-orig]"
        fi
        ;;
    decrypt)
        if [[ -n "$2" ]]; then
            file_decrypt "$2" "$delete_original_file"
        else
            echo "Usage: $0 decrypt <FILE_TO_DECRYPT> [--rm-orig]"
        fi
        ;;
    pb_encrypt)
        if [[ -n "$2" ]]; then
            clipboard_encrypt "$2"
        else
            echo "Usage: copy to clipboard, then $0 pb_encrypt <RECIPIENT_EMAIL>"
        fi
        ;;
    pb_decrypt)
        clipboard_decrypt
        ;;
    *)
        echo "Invalid option: $1"
        show_help
        ;;
esac
