#!/bin/bash

key_lookup() {
    if ! gpg --list-keys "$1" > /dev/null/ 2>&1; then
        echo "Recipient key not found! Remember to import first."
    fi
}

show_help() {
    echo "It is recommended to make the script an alias!"
    echo "Usage: $0 {encrypt|decrypt} <arguments>"
    echo "Options:"
    echo "   encrypt <RECIPIENT_EMAIL> <FILE_TO_ENCRYPT> Encrypt + sign to a recipient"
    echo "   decrypt <FILE_TO_DECRYPT>                   Decrypt a given file"
    echo "   -h, --help                                  Display this help message"
}

file_encrypt() {
    local recipient="$1"
    local file_input="$2"
    local file_output="${file_input}.asc"

    key_lookup "$recipient"

    gpg --output "$file_output" \
        --encrypt --sign --armor \
        --recipient "$recipient" "$file_input"

    echo "'$file_input' encrypted and signed as '$file_output' to '$recipient'."
}

file_decrypt() {
    local file_encrypted="$1"
    local file_output="${file_encrypted}.decrypted"

    gpg --output "$file_output" \
        --decrypt "$file_encrypted"

    echo "'$file_encrypted' decrypted as '$file_output'."
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    show_help
    exit 0
fi

case "$1" in
    encrypt)
        if [[ -n "$2" && -n "$3" ]]; then
            file_encrypt "$2" "$3"
        else
            echo "Usage: $0 encrypt <RECIPIENT_EMAIL> <FILE_TO_ENCRYPT>"
        fi
        ;;
    decrypt)
        if [[ -n "$2" ]]; then
            file_decrypt "$2"
        else
            echo "Usage: $0 decrypt <FILE_TO_DECRYPT>"
        fi
        ;;
    *)
        echo "Invalid option: $1"
        show_help
        ;;
esac
